#include <iostream>
#include <cstring>
#include <ctime>
#include <cctype>

using namespace std;

struct Board
{
    int answer[4];
    int attempts;
};

void board_init(struct Board *b)
{
    srand (time(0));
    int range = 6 - 1 + 1;
    int k = 0;
    int i;
    int random;
    for (i=0; i<4; i++)
    {
        random = (rand() % range) + 1;
        b->answer[i] = random; k++;
    }

    //print for debugging
    for (i=0; i<4; i++)
    {
        cout << b->answer[i] << ' ';
    }

    b->attempts = 0;
}

int get_user_guess(int guess[])
{
    bool flag = false;

    int number;
    int digit_check = 0;
    cout << "Make your guess:" << endl;
    cin >> number;

    while (!flag)
    {
        for (int i=3; i>=0; i--)
        {
            guess[i] = number % 10;
            number /= 10;
        }
        for (int i=0; i<4; i++)
        {
            if (guess[i] <= 0 || guess[i] >= 7)
            {
                cout << "A number you entered isn't acceptable. Enter a four digit number using 1-6." << endl;
                cin >> number;
                break;
            }
            else
            {
                digit_check++;
                if (digit_check == 4)
                {
                    flag = true;
                }
                continue;
            }
        }
    }
    return guess[4];
}

void answer_verification(struct Board *b, int guess[], int *right_number_right_position, int *right_number_wrong_position)
{
    b->attempts++;
    right_number_right_position = 0;
    right_number_wrong_position = 0;

    for (int i=0; i<4; i++)
    {
        if (guess[i] == b->answer[0])
        {
            *right_number_right_position++;
        }
        else if (guess[i] == b->answer[1])
        {
            *right_number_right_position++;
        }
        else if (guess[i] == b->answer[2])
        {
            *right_number_right_position++;
        }
        else if (guess[i] == b->answer[3])
        {
            *right_number_right_position++;
        }
        else
        {
            *right_number_wrong_position++;
        }
    }


}

struct Board b;

int main()
{

    bool done = false;
    int right_number_right_position = 0;
    int right_number_wrong_position = 0;
    int guess[4];

    board_init(&b);

    cout << "Mastermind rules:\n" << endl;
    cout << "The player has 10 turns to guess the 4 digit sequence generated by the program. The sequence is 4 digits and is\nconstructed with any number 1-6, and numbers can be repeated. Ex: 1152" << endl;

    while (!done)
    {
        get_user_guess(guess);

        //for debugging
        for (int i=0; i<4; i++)
        {
            cout << guess[i] << ' ';
        }

        answer_verification(&b, guess, &right_number_right_position, &right_number_wrong_position);



        if (b.attempts > 10)
        {
            cout << "Out of turns." << endl;
            done = true;
        }
        else if (right_number_right_position == 4)
        {
            cout << "You win!" << endl;
            done = true;
        }
    }

    return 0;
}
