#include <iostream>
#include <cstring>
#include <ctime>
#include <cctype>

using namespace std;

struct Board
{
    int answer[4];
    int attempts;
};

void board_init(struct Board *b)
{
    srand (time(0));
    int range = 6 - 1 + 1;
    int k = 0;
    int i;
    int random;
    for (i=0; i<4; i++)
    {
        random = (rand() % range) + 1;
        b->answer[i] = random; k++;
    }

    //print for debugging

    for (i=0; i<4; i++)
    {
        cout << b->answer[i] << ' ';
    }

    b->attempts = 1;
}

int get_user_guess(struct Board *b, int guess[])
{
    bool flag = false;

    int number;
    int digit_check = 0;
    cout << "\nTurn: " << b->attempts << endl;
    cout << "Make your guess:" << endl;
    cin >> number;

    while (!flag)
    {
        for (int i=3; i>=0; i--)
        {
            guess[i] = number % 10;
            number /= 10;
        }
        for (int i=0; i<4; i++)
        {
            if (guess[i] <= 0 || guess[i] >= 7)
            {
                cout << "A number you entered isn't acceptable. Enter a four digit number using 1-6." << endl;
                cin >> number;
                break;
            }
            else
            {
                digit_check++;
                if (digit_check == 4)
                {
                    flag = true;
                }
                continue;
            }
        }
    }
    return guess[4];
}

int answer_verification(struct Board *b, int guess[4], int right_number_right_position, int right_number_wrong_position)
{
    b->attempts++;
    right_number_right_position = 0;
    right_number_wrong_position = 0;
    for (int i=0; i<4;)
    {
        for (int j=0; j<4; j++)
        {
            if (guess[j] == b->answer[i])
            {
                right_number_right_position++;
                i++;
            }
            else
            {
                right_number_wrong_position++;
                i++;
            }
        }
    }
    return right_number_right_position;
}

int answer_verification2(struct Board *b, int guess[4], int right_number_right_position, int right_number_wrong_position, int wrong_number)
{
    right_number_right_position = 0;
    right_number_wrong_position = 0;
    wrong_number = 0;
    for (int i=0; i<4; i++)
    {
        if (guess[i] == b->answer[0])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[1])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[2])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[3])
        {
            right_number_wrong_position++;
        }
        else
        {
            wrong_number++;
        }
    }
    return right_number_wrong_position;
}

int answer_verification3(struct Board *b, int guess[4], int right_number_wrong_position, int wrong_number)
{
    right_number_wrong_position = 0;
    wrong_number = 0;
    for (int i=0; i<4; i++)
    {
        if (guess[i] != b->answer[i])
        {
            wrong_number++;
        }
        else
        {
            right_number_wrong_position++;
        }
    }
    return wrong_number;
}

int repeat_checker(int guess[4], int repeat_check, int wrong_number)
{
    repeat_check = 0;
    for (int i=0; i<4; i++)
    {
        for (int j=0; j<4; j++)
        {
            if (guess[j+1] == guess[i])
            {
                repeat_check++;
            }
            else
            {
                wrong_number++;
            }
            if (repeat_check == 3)
            {
                return repeat_check;
            }
        }
    }
    return repeat_check;
}

struct Board b;

int main()
{
    bool done = false;
    bool flag = true;
    int right_number_right_position = 0;
    //int* rnrp;
    //rnrp = &right_number_right_position;

    int right_number_wrong_position = 0;
    //int* rnwp;
    //rnwp = &right_number_wrong_position;
    int wrong_number = 0;
    int repeat_check = 0;
    int guess[4];

    board_init(&b);

    cout << "Mastermind rules:\n" << endl;
    cout << "The player has 10 turns to guess the 4 digit sequence generated by the program. The sequence is 4 digits and is\nconstructed with any number 1-6, and numbers can be repeated. Ex: 1156" << endl;

    while (!done)
    {
        get_user_guess(&b, guess);
/*
        //for debugging
        for (int i=0; i<4; i++)
        {
            cout << guess[i] << ' ';
        }
*/
        //Call for mentioned function
        right_number_right_position = answer_verification(&b, guess, right_number_right_position, right_number_wrong_position);
        right_number_wrong_position = answer_verification2(&b, guess, right_number_right_position, right_number_wrong_position, wrong_number);
        //wrong_number = answer_verification3(&b, guess, right_number_wrong_position, wrong_number);
        right_number_wrong_position = (right_number_wrong_position-right_number_right_position);
        wrong_number = (4-(right_number_right_position+right_number_wrong_position));

        repeat_check = repeat_checker(guess, repeat_check, wrong_number);

        if (repeat_check > 0)
        {
            right_number_wrong_position = (right_number_wrong_position-repeat_check);
        }

        if (right_number_wrong_position < 0)
        {
            right_number_wrong_position = 0;
        }

        for (int i=right_number_right_position; i>=1; i--)
        {
            cout << "Right number, right position." << endl;
        }

        flag = true;
        do
        {
            if (right_number_right_position == 4)
            {
                flag = false;
            }
            else
            {
                for (int i=right_number_wrong_position; i>=1; i--)
                {
                    cout << "Right number, wrong position." << endl;
                }
                flag = false;
            }
        } while (flag);

        if (b.attempts > 10)
        {
            cout << "Out of turns." << endl;
            cout << "The sequence was: " << endl;
            for (int i=0; i<4; i++)
            {
                cout << b.answer[i] << ' ';
            }
            done = true;
        }
        else if (right_number_right_position == 4)
        {
            cout << "You win!" << endl;
            cout << "The sequence was: " << endl;
            for (int i=0; i<4; i++)
            {
                cout << b.answer[i] << ' ';
            }
            done = true;
        }
    }

    return 0;
}
