#include <iostream>
#include <cstring>
#include <ctime>
#include <cctype>

using namespace std;

struct Board
{
    //Generated sequence and turn counter
    int answer[4];
    int attempts;
};

void board_init(struct Board *b)
{
    //Randomly generate sequence
    //Range 1-6, length 4 digits
    srand (time(0));
    int range = 6 - 1 + 1;
    int k = 0;
    int i;
    int random;
    for (i=0; i<4; i++)
    {
        random = (rand() % range) + 1;
        b->answer[i] = random; k++;
    }
    //Set turn counter to 1
    b->attempts = 1;
}

int get_user_guess(struct Board *b, int guess[])
{
    bool flag = false;
    int number;
    int digit_check = 0;
    //Display current turn
    cout << "\nTurn: " << b->attempts << endl;
    //User inputs guess
    cout << "Make your guess:" << endl;
    cin >> number;

    while (!flag)
    {
        //Convert user guess of "xxxx" to array of {x,x,x,x}
        for (int i=3; i>=0; i--)
        {
            guess[i] = number % 10;
            number /= 10;
        }
        for (int i=0; i<4; i++)
        {
            //Check if a user input digit is inside desired range
            if (guess[i] <= 0 || guess[i] >= 7)
            {
                cout << "A number you entered isn't acceptable. Enter a four digit number using 1-6." << endl;
                cin >> number;
                break;
            }
            else
            {
                //Check through each digit in user input until entire input is verified
                digit_check++;
                if (digit_check == 4)
                {
                    flag = true;
                }
                continue;
            }
        }
    }
    return guess[4];
}

int answer_verification(struct Board *b, int guess[4], int right_number_right_position, int right_number_wrong_position)
{
    //Increase turn counter
    b->attempts++;
    //Reset counters to 0
    right_number_right_position = 0;
    right_number_wrong_position = 0;
    //Find numbers of equal value and equal position
    for (int i=0; i<4;)
    {
        for (int j=0; j<4; j++)
        {
            if (guess[j] == b->answer[i])
            {
                right_number_right_position++;
                i++;
            }
            else
            {
                //Throwaway option in order to prevent infinite loop
                right_number_wrong_position++;
                i++;
            }
        }
    }
    return right_number_right_position;
}

int answer_verification2(struct Board *b, int guess[4], int right_number_right_position, int right_number_wrong_position)
{
    //Reset counters to 0
    right_number_right_position = 0;
    right_number_wrong_position = 0;
    //Find numbers that are of equal value
    for (int i=0; i<4; i++)
    {
        if (guess[i] == b->answer[0])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[1])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[2])
        {
            right_number_wrong_position++;
        }
        else if (guess[i] == b->answer[3])
        {
            right_number_wrong_position++;
        }
        else
        {
            //Throwaway option in order to prevent infinite loop
            right_number_right_position++;
        }
    }
    return right_number_wrong_position;
}

//Store answer and turn count
struct Board b;

int main()
{
    //Variables
    bool done = false;
    bool flag = true;
    int right_number_right_position = 0;
    int right_number_wrong_position = 0;
    //User guess
    int guess[4];

    //Create sequence and begin game
    board_init(&b);

    cout << "Mastermind rules:\n" << endl;
    cout << "The player has 10 turns to guess the 4 digit sequence generated by the program. The sequence is 4 digits and is\nconstructed with any number 1-6, and numbers can be repeated. Ex: 1156" << endl;

    while (!done)
    {
        //User inputs their guess
        get_user_guess(&b, guess);

        //Determine which numbers in user guess correspond with which numbers in the answer
        //Function 1
        right_number_right_position = answer_verification(&b, guess, right_number_right_position, right_number_wrong_position);
        //Function 2
        right_number_wrong_position = answer_verification2(&b, guess, right_number_right_position, right_number_wrong_position);
        //Calculate actual value of right_number_wrong_position
        right_number_wrong_position = (right_number_wrong_position-right_number_right_position);

        //Provide feedback
        for (int i=right_number_right_position; i>=1; i--)
        {
            cout << "Right number, right position." << endl;
        }

        //Provide feedback continued
        flag = true;
        do
        {
            //If guess == answer, no reason to continue through this
            if (right_number_right_position == 4)
            {
                flag = false;
            }
            else
            {
                for (int i=right_number_wrong_position; i>=1; i--)
                {
                    cout << "Right number, wrong position." << endl;
                }
                flag = false;
            }
        } while (flag);

        //Determine if game is over
        //User runs out of turns
        if (b.attempts > 10)
        {
            cout << "\nOut of turns." << endl;
            cout << "The sequence was: " << endl;
            for (int i=0; i<4; i++)
            {
                cout << b.answer[i] << ' ';
            }
            done = true;
        }
        //User correctly guesses the answer
        else if (right_number_right_position == 4)
        {
            cout << "\nYou win!" << endl;
            cout << "The sequence was: " << endl;
            for (int i=0; i<4; i++)
            {
                cout << b.answer[i] << ' ';
            }
            done = true;
        }
    }
    return 0;
}
